const CLIENT: string = '';

export const CLIENT_ROUTE_NAME = {
  WAITFORCONFIRMATON: 'auth/verifytoken',
  SIGNIN: 'signin',
  REGISTER: 'register',
  FORGOTPASSWORD: 'forgotpassword',
  CHANGEPASSWORD: 'auth/forgotpassword-token',
  // DASHBOARD: '',
  NOT_FOUND_ERR: 'not-found',
  HOME: '',
  PROFILE: 'profile',
  OTHERPROFILE: 'other-profile',
  FRIENDS: 'friends',
  POST: 'post',
};

export const CLIENT_ROUTE_PATH = {
  SIGNIN: `${CLIENT}/${CLIENT_ROUTE_NAME.SIGNIN}`,
  REGISTER: `${CLIENT}/${CLIENT_ROUTE_NAME.REGISTER}`,
  FORGOTPASSWORD: `${CLIENT}/${CLIENT_ROUTE_NAME.FORGOTPASSWORD}`,
  CHANGEPASSWORD: `${CLIENT}/${CLIENT_ROUTE_NAME.CHANGEPASSWORD}`,
  WAITFORCONFIRMATON: `${CLIENT}/${CLIENT_ROUTE_NAME.WAITFORCONFIRMATON}`,
  // DASHBOARD: `${CLIENT}/${CLIENT_ROUTE_NAME.DASHBOARD}`,
  NOT_FOUND_ERR: `${CLIENT}/${CLIENT_ROUTE_NAME.NOT_FOUND_ERR}`,
  HOME: `${CLIENT}/${CLIENT_ROUTE_NAME.HOME}`,
  PROFILE: `${CLIENT}/${CLIENT_ROUTE_NAME.PROFILE}`,
  OTHERPROFILE: `${CLIENT}/${CLIENT_ROUTE_NAME.OTHERPROFILE}`,
  FRIENDS: `${CLIENT}/${CLIENT_ROUTE_NAME.FRIENDS}`,
  POST: `${CLIENT}/${CLIENT_ROUTE_NAME.POST}`,
};
